=== SamikshyaChhetri/web-assignment/Labwork_Samikshya/employees.dtd
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, address, phone, designation, salary)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT designation (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== SamikshyaChhetri/web-assignment/Labwork_Samikshya/lab_4.8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<?xml-stylesheet type="text/xsl" href="employees.xslt"?>
<employees>
    <employee>
        <name>Samikshya Baniya</name>
        <address>Patan,Lalitpur</address>
        <phone>+977-9875467876</phone>
        <designation>Software Engineer</designation>
        <salary>90000</salary>
    </employee>
    <employee>
        <name>Jane Smith</name>
        <address>456 Maple Avenue</address>
        <phone>555-5678</phone>
        <designation>Project Manager</designation>
        <salary>75000</salary>
    </employee>
    <employee>
        <name>Michael Brown</name>
        <address>789 Oak Street</address>
        <phone>555-9101</phone>
        <designation>Analyst</designation>
        <salary>50000</salary>
    </employee>
</employees>
